Introduction to Numpy

In [3]:
#Numpy is a power


In [2]:
#Importing Numpy
import numpy as np

In [4]:
#Creating array using numPy
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
#creating array using numpy
arr= np.array([[1,2,3,4,5]])
print(arr)
print(type(arr))
print(arr.shape)

[[1 2 3 4 5]]
<class 'numpy.ndarray'>
(1, 5)


In [7]:
mat=np.array([[11,22,33],[22,33,44],[44,55,66]])
print(mat)
print(type(mat))
print(mat.shape)

[[11 22 33]
 [22 33 44]
 [44 55 66]]
<class 'numpy.ndarray'>
(3, 3)


In [16]:
#Creating 2D array
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(type(arr))
print(arr)

(3, 3)
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
#Array  of Zeros
zeros_array = np.zeros((3,3))
print(zeros_array)


#Array of ones
ones_array = np.ones((3,3))
print(ones_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
#Indentity matrix
idn_matrix=np.eye(3)
print(idn_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
#Create  a random matrix with values 0 and 1
rows=5
cols=5
random_matrix = np.random .rand()

FETCHING ARRAY OF INDEXES

In [24]:
#array indexing...
arr=np.array([1,2,3,4])
print(arr[2])

#
arr2D = np.array([[11,22,33],[44,55,66],[77,88,99]])
print(arr2D[1,2])

3
66


In [27]:
print(arr2D[1]) #fetch the first row..
print(arr2D[:,1]) #fetch the first col..
print(arr2D[:,(1,2)])  #fetch from oth row to 1st row...

[44 55 66]
[22 55 88]
[[22 33]
 [55 66]
 [88 99]]


In [31]:
import numpy as np
a = np.array([[1,2,30],[10,15,4],[11,22,33]])
print("The array:" ,a)
print("The maximum elements of columns:",a.max(axis = 0 ))
print("The minimum element of rows",a.min(axis =1))
print("The average element of rows",a.mean(axis =1))
print("The sum of all rows",a.sum(axis =1))

The array: [[ 1  2 30]
 [10 15  4]
 [11 22 33]]
The maximum elements of columns: [11 22 33]
The minimum element of rows [ 1  4 11]
The average element of rows [11.          9.66666667 22.        ]
The sum of all rows [33 29 66]


In [32]:
#Normalize the matrix...
colMean = np.mean(a,axis=0)
print (a)
print(colMean)

[[ 1  2 30]
 [10 15  4]
 [11 22 33]]
[ 7.33333333 13.         22.33333333]


In [33]:
#Substract

In [34]:
#Iterative 2D array
arr2D=np.array([[1,2,3,4],[11,22,33,44],[99,88,90,44]])

In [49]:
#Matrix opeartion using numpy
import numpy as np

#Define mtarices
A=np.array([[1,2],
          [3,4]])
B=np.array([[2,0],
          [1,3]])
#Matrix opeartions
C=A +B
D=A-B
M=A+B
E= A @ B
J= A*B
F=np.dot(A,B)
G=A.T #np.transpose(A)
H=np.linalg.inv(A)
det_A = np.linalg.det(A)
#eigenvalues,eignvectors =np.linalg.elg(A)
U,s,Vt = np.linalg.svd(A)
b=np.array([1,2])
x=np.linalg.solve(A,b)
I = np.eye(2)
D=np.diag([1,2])

#print results
print(C)
print(D)
print(M)
print(E)
print(J)
print(H)
print(G)

[[3 2]
 [4 7]]
[[1 0]
 [0 2]]
[[3 2]
 [4 7]]
[[ 4  6]
 [10 12]]
[[ 2  0]
 [ 3 12]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1 3]
 [2 4]]


Numpy and Linear Algebra

In [53]:
#Importing numpy as np
import numpy as np
A = np.array([[6,1,1],
            [4,3,-1],
            [2,8,7]])

#Rank of the matrix
print("Rank of A :",np.linalg.matrix_rank(A))

#Traces

Rank of A : 3


Implementation of KNN algorithm

In [59]:
#Create a numpy matrix ..data set ...
A = np.array([[1,4,5,4],
              [5,8,9,14],
              [6,7,11,13],
              [1,4,5,3],
              [5,8,9,14],
              [4,7,8,13],
              [1,4,6,4],
              [5,5,4,5],
              [5,8,9,14],
              [6,7,11,12]])
class_level = [1,2,2,1,2,2,1,1,2,2] #Assosiated class level
row,col = A . shape

In [1]:
import numpy as np
import math
#compute the modulation distance..
def distance(x,y):
    sum=0.0
    for i in range(len(x)):
        sum=sum + (x[i] - y[i]) * (x[i] - y[i])
        return math.sqrt(sum)

In [2]:
import numpy as np

def distance(a, b):
    return np.linalg.norm(a - b)  # Euclidean distance function

def knn_classification(A, new_sample, k, class_labels):
    # A is the dataset, new_sample is the point to classify, k is the number of neighbors
    rows, cols = A.shape

    # Get the distance from all samples of the dataset and store in d
    distances = []
    for i in range(rows):
        dist = distance(new_sample, A[i, :-1])  # Exclude the class label column
        distances.append(dist)
    
    # Print the distances (optional)
    print("The distances from all points are:\n", distances)

    # Get the indices of the k-nearest neighbors (sorted by distance)
    index = np.argsort(distances)
    print("Sorted indices:\n", index)

    # Count the occurrences of class labels among the k-nearest neighbors
    count_class_1 = 0
    count_class_2 = 0

    for i in range(k):
        # Check the class of the nearest neighbors
        if class_labels[index[i]] == 1:
            count_class_1 += 1
        else:
            count_class_2 += 1
    
    # Return the class with the majority votes
    if count_class_1 > count_class_2:
        return 1
    else:
        return 2


In [ ]:
#test the model
sample_1 = [1,4,5,4] #new sample..
